# Generated by Django 4.1 on 2022-11-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjaxField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name field', max_length=20)),
                ('picture', models.ImageField(default='wink.jpg', upload_to='profile_images')),
            ],
        ),
    ]
